loop do
  
  cmd("EPS_DIST DOMSWITCH with PD_COM1 TOGGLE")
  cmd("EPS_DIST DOMSWITCH with PD_COM2 TOGGLE")
  cmd("EPS_DIST DOMSWITCH with PD_RAHS TOGGLE")
  cmd("EPS_DIST DOMSWITCH with PD_BDOT TOGGLE")
  cmd("EPS_DIST DOMSWITCH with PD_ESTIM TOGGLE")
  cmd("EPS_DIST DOMSWITCH with PD_WHEELS TOGGLE")
  cmd("EPS_DIST DOMSWITCH with PD_EPS TOGGLE")
  cmd("EPS_DIST DOMSWITCH with PD_PPT TOGGLE")
  
  


end
