cmd("EPS_DIST COMMONCMD with EXPECTED_MODULE MOD_EPS_DIST")
cmd("EPS_GEN COMMONCMD with EXPECTED_MODULE MOD_EPS_GEN")
cmd("EPS_BATT COMMONCMD with EXPECTED_MODULE MOD_EPS_BATT")

wait(2)

if (tlm("EPS_DIST META COMM_MATCHSTATE") ==  'MATCHED' && \
    tlm("EPS_GEN META COMM_MATCHSTATE") ==  'MATCHED' && \
    tlm("EPS_BATT META COMM_MATCHSTATE") ==  'MATCHED')

  puts("-- ALL BOARDS MATCHED --")
else
  puts("** MATCH VIOLATION IN AT LEAST ONE BOARD **")
end
